<?php

$bibleDefs['njb'] = [

	"outFile"		=> "NewJerusalemBible.html",

	"mainTitle" 	=> "New Jerusalem Bible",

	"msgLoading" 	=> "loading...",
	"msgBack" 		=> "Back",
	"msgTop" 		=> "top",

	"books" 		=> [

		"Pentateuch" => [
			["Gen", "Genesis"],
			["Exo", "Exodus"],
			["Lev", "Leviticus"],
			["Num", "Numbers"],
			["Deu", "Deuteronomy"]
		],
		"Historical" => [
			["Jos", "Joshua"],
			["Jdg", "Judges"],
			["Rut", "Ruth"],
			["1Sa", "1 Samuel"],
			["2Sa", "2 Samuel"],
			["1Ki", "1 Kings"],
			["2Ki", "2 Kings"],
			["1Ch", "1 Chronicles"],
			["2Ch", "2 Chronicles"],
			["Ezr", "Ezra"],
			["Neh", "Nehemiah"],
			["Tob", "Tobit"],
			["Jdt", "Judith"],
			["Est", "Esther"],
			["1Ma", "1 Maccabees"],
			["2Ma", "2 Maccabees"],
		],
		"Poetic" => [
			["Job", "Job"],
			["Psa", "Psalms"],
			["Pro", "Proverbs"],
			["Ecc", "Ecclesiastes"],
			["Sol", "Song of Solomon"],
			["Wis", "Wisdom"],
			["Sir", "Sirach"],
		],
		"Prophetic" => [
			["Isa", "Isaiah"],
			["Jer", "Jeremiah"],
			["Lam", "Lamentations"],
			["Bar", "Baruch"],
			["Eze", "Ezekiel"],
			["Dan", "Daniel"],
			["Hos", "Hosea"],
			["Joe", "Joel"],
			["Amo", "Amos"],
			["Oba", "Obadiah"],
			["Jon", "Jonah"],
			["Mic", "Micah"],
			["Nah", "Nahum"],
			["Hab", "Habakkuk"],
			["Zep", "Zephaniah"],
			["Hag", "Haggai"],
			["Zec", "Zechariah"],
			["Mal", "Malachi"],
		],
		"New Testament" => [
			["Mat", "Matthew"],
			["Mar", "Mark"],
			["Luk", "Luke"],
			["Joh", "John"],
			["Act", "Acts"],
			["Rom", "Romans"],
			["1Co", "1 Corinthians"],
			["2Co", "2 Corinthians"],
			["Gal", "Galatians"],
			["Eph", "Ephesians"],
			["Phi", "Philippians"],
			["Col", "Colossians"],
			["1Th", "1 Thessalonians"],
			["2Th", "2 Thessalonians"],
			["1Ti", "1 Timothy"],
			["2Ti", "2 Timothy"],
			["Tit", "Titus"],
			["Phm", "Philemon"],
			["Heb", "Hebrews"],
			["Jam", "James"],
			["1Pe", "1 Peter"],
			["2Pe", "2 Peter"],
			["1Jo", "1 John"],
			["2Jo", "2 John"],
			["3Jo", "3 John"],
			["Jud", "Jude"],
			["Rev", "Revelation"]
		]
	]
];

$bibleDefs['suv'] = [

	"outFile"		=> "SwahiliUnionBible.html",

	"mainTitle" 	=> "Swahili Union Bible",

	"msgLoading" 	=> "loading...",
	"msgBack" 		=> "Rudi",
	"msgTop" 		=> "juu",

	"books" 		=> [

		"Vitabu 5 vya Musa" => [
			["Mwa", "Mwanzo"],
			["Kut", "Kutoka"],
			["Law", "Mambo ya Walawi"],
			["Hes", "Hesabu"],
			["Kum", "Kumbukumbu la Torati"],
		],
		"Vitabu vya Historia" => [
			["Yos", "Yoshua"],
			["Amu", "Waamuzi"],
			["Rut", "Ruthu"],
			["1Sam", "1 Samweli"],
			["2Sam", "2 Samweli"],
			["1Fal", "1 Wafalme"],
			["2Fal", "2 Wafalme"],
			["1Nya", "1 Mambo ya Nyakati"],
			["2Nya", "2 Mambo ya Nyakati"],
			["Ezr", "Ezra"],
			["Neh", "Nehemia"],
			["Est", "Esta"],
			["Ayu", "Ayubu"],
		],
		"Vitabu vya hekima" => [
			["Zab", "Zaburi"],
			["Mit", "Mithali"],
			["Mhu", "Mhubiri"],
			["Wim", "Wimbo Ulio Bora"],
		],
		"Vitabu vya kinabii" => [
			["Isa", "Isaya"],
			["Yer", "Yeremia"],
			["Omb", "Maombolezo"],
			["Eze", "Ezekieli"],
			["Dan", "Danieli"],
			["Hos", "Hosea"],
			["Yoe", "Yoeli"],
			["Amo", "Amosi"],
			["Oba", "Obadia"],
			["Yon", "Yona"],
			["Mik", "Mika"],
			["Nah", "Nahumu"],
			["Hab", "Habakuki"],
			["Sef", "Sefania"],
			["Hag", "Hagai"],
			["Zek", "Zekaria"],
			["Mal", "Malaki"],
		],
		"Agano Jipya" => [
			["Mt", "Mathayo"],
			["Mk", "Marko"],
			["Lk", "Luka"],
			["Yn", "Yohana"],
			["Mdo", "Matendo ya Mitume"],
			["Rum", "Warumi"],
			["1Kor", "1 Wakorintho"],
			["2Kor", "2 Wakorintho"],
			["Gal", "Wagalatia"],
			["Efe", "Waefeso"],
			["Flp", "Wafilipi"],
			["Kol", "Wakolosai"],
			["1The", "1 Wathesalonike"],
			["2The", "2 Wathesalonike"],
			["1Tim", "1 Timotheo"],
			["2Tim", "2 Timotheo"],
			["Tit", "Tito"],
			["Flm", "Filemoni"],
			["Ebr", "Waebrania"],
			["Yak", "Yakobo"],
			["1Pet", "1 Petro"],
			["2Pet", "2 Petro"],
			["1Yoh", "1 Yohana"],
			["2Yoh", "2 Yohana"],
			["3Yoh", "3 Yohana"],
			["Yda", "Yuda"],
			["Ufu", "Ufunuo wa Yohana"],

			/*["Tob", "Tobiti"],
			["Yud", "Yudithi"],
			["Hek", "Hekima ya Sulemani"],
			["YbS", "Hekima ya Yoshua Bin Sira"],
			["Bar", "Baruku"],
			["1Mak", "1 Wamakabayo"],
			["2Mak", "2 Wamakabayo"],*/
		]
	]
];